<a href="https://colab.research.google.com/github/juandavidarcila/Metodos-Computacionales/blob/main/Semana6/Actividad11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.special import factorial
import sympy as sym

In [ ]:
#f = lambda x: 6*x**2

In [ ]:
#w0 = np.array([1.,1.])
#x0 = np.array([-1./np.sqrt(3), 1./np.sqrt(3)])

In [ ]:
#I = np.sum(w0*f(x0))
#I

In [ ]:
#I = np.sin(1) - np.sin(-1)
#I

In [ ]:
def GetNewtonMethod(f,df,xn,itmax = 1000, precision=1e-14):

    error = 1.
    it = 0

    while error >= precision and it < itmax:

      dfx = df(xn)

      # Evitar división por cero
      if np.abs(dfx) < 1e-16:
            print("Derivada cercana a cero. Método falla.")
            return False

      xn1 = xn - f(xn)/df(xn)
      error = np.abs( xn1-xn )

      xn  = xn1
      it += 1


    if it == itmax:
        return False
    else:
        return xn

In [ ]:
def GetAllRoots(f, df, x, tolerancia_decimales=8, tol_unicidad=1e-6):

    Roots = []

    for x0 in x:

        root = GetNewtonMethod(f, df, x0)

        if root is not False:

            # Redondeamos
            croot = np.round(root, tolerancia_decimales)

            # Verificamos que no esté ya (con tolerancia)
            if not any(np.isclose(croot, r, atol=tol_unicidad) for r in Roots):
                Roots.append(croot)

    Roots = np.array(Roots)
    Roots.sort()

    return Roots

In [ ]:
def GetLegendre(n):

  x = sym.Symbol('x',Real=True)
  y = sym.Symbol('y',Real=True)

  y = (x**2 - 1)**n

  p = sym.diff(y,x,n)/(2**n * factorial(n))

  return p

In [ ]:
GetLegendre(2)

1.5*x**2 - 0.5

In [ ]:
def GetLaguerre(n):
  x = sym.Symbol('x',Real=True)
  y = sym.Symbol('y',Real=True)

  y = sym.exp(-x)*x**n

  p = sym.diff(y,x,n)*(sym.exp(x)/factorial(n))

  return p.simplify()

In [ ]:
GetLaguerre(1)

1.0 - 1.0*x

In [ ]:
Laguerre = []
DLaguerre = []

x = sym.Symbol('x',Real=True)
n=7

for i in range(n+1):

    poly = GetLaguerre(i)

    Laguerre.append(poly)
    DLaguerre.append(sym.diff(poly,x))

In [ ]:
Laguerre[n]

-0.000198412698412698*x**7 + 0.00972222222222222*x**6 - 0.175*x**5 + 1.45833333333333*x**4 - 5.83333333333333*x**3 + 10.5*x**2 - 7.0*x + 1.0

In [ ]:
def GetRootsPolynomial(n,xi,poly,dpoly):

    x = sym.Symbol('x',Real=True)
    pn = sym.lambdify([x],poly[n],'numpy')
    dpn = sym.lambdify([x],dpoly[n],'numpy')

    Roots = GetAllRoots(pn,dpn,xi)

    return Roots

In [ ]:
xi = np.linspace(0,40,100,dtype=np.longdouble)
Roots = GetRootsPolynomial(n,xi,Laguerre,DLaguerre)
Roots

array([ 0.19304368,  1.0266649 ,  2.56787674,  4.90035308,  8.18215344,
       12.73418029, 19.39572786], dtype=float128)

In [ ]:
# Calculando usando el paquete
a = 0
b = 0.25*np.pi
f = lambda x: np.sin(x)

In [ ]:
Roots, Weights = np.polynomial.legendre.leggauss(7)
t = 0.5*( (b-a)*Roots + b + a )
Integral = 0.5*(b-a)*np.sum(Weights*f(t))
Roots

array([-0.94910791, -0.74153119, -0.40584515,  0.        ,  0.40584515,
        0.74153119,  0.94910791])

In [ ]:
Weights

array([0.12948497, 0.27970539, 0.38183005, 0.41795918, 0.38183005,
       0.27970539, 0.12948497])

In [ ]:
print('{:.70f}'.format(Integral))
print('{:.70f}'.format(1-np.cos(0.25*np.pi)))

0.2928932188134524272626890706305857747793197631835937500000000000000000
0.2928932188134524272626890706305857747793197631835937500000000000000000
